// Mocks generated by Mockito from annotations
// in pulse/test/notifiers/expense_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pulse/features/expense/models/expense.dart' as _i3;
import 'package:pulse/features/expense/services/expense_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpense_1 extends _i1.SmartFake implements _i3.Expense {
  _FakeExpense_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseService extends _i1.Mock implements _i4.ExpenseService {
  MockExpenseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
    Invocation.getter(#dio),
    returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
  ) as _i2.Dio);

  @override
  _i5.Future<List<_i3.Expense>> fetchAll() => (super.noSuchMethod(
    Invocation.method(#fetchAll, []),
    returnValue: _i5.Future<List<_i3.Expense>>.value(<_i3.Expense>[]),
  ) as _i5.Future<List<_i3.Expense>>);

  @override
  _i5.Future<_i3.Expense> createExpense(_i3.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(#createExpense, [expense]),
        returnValue: _i5.Future<_i3.Expense>.value(
          _FakeExpense_1(this, Invocation.method(#createExpense, [expense])),
        ),
      ) as _i5.Future<_i3.Expense>);

  @override
  _i5.Future<_i3.Expense> updateExpense(_i3.Expense? expense) =>
      (super.noSuchMethod(
        Invocation.method(#updateExpense, [expense]),
        returnValue: _i5.Future<_i3.Expense>.value(
          _FakeExpense_1(this, Invocation.method(#updateExpense, [expense])),
        ),
      ) as _i5.Future<_i3.Expense>);

  @override
  _i5.Future<void> deleteExpense(String? id) => (super.noSuchMethod(
    Invocation.method(#deleteExpense, [id]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);
}
